server:
  port: 8090
  error:
    include-binding-errors: always
    include-message: always


spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: auction
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB