server:
  port: 8090
  error:
    include-binding-errors: always
    include-message: always


spring:
  data:
    mongodb:
      authentication-database: admin
      username: user
      password: pass
      database: auction
      port: 27017
      host: mongodb
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB